// Code generated by ent, DO NOT EDIT.

package doctor

import (
	"auth/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldID, id))
}

// DoctorID applies equality check predicate on the "doctor_id" field. It's identical to DoctorIDEQ.
func DoctorID(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldDoctorID, v))
}

// DoctorIDEQ applies the EQ predicate on the "doctor_id" field.
func DoctorIDEQ(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldDoctorID, v))
}

// DoctorIDNEQ applies the NEQ predicate on the "doctor_id" field.
func DoctorIDNEQ(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldDoctorID, v))
}

// DoctorIDIn applies the In predicate on the "doctor_id" field.
func DoctorIDIn(vs ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldDoctorID, vs...))
}

// DoctorIDNotIn applies the NotIn predicate on the "doctor_id" field.
func DoctorIDNotIn(vs ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldDoctorID, vs...))
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newEmployeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.NotPredicates(p))
}
