// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auth/ent/employee"
	"auth/ent/nurse"
	"auth/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NurseQuery is the builder for querying Nurse entities.
type NurseQuery struct {
	config
	ctx          *QueryContext
	order        []nurse.OrderOption
	inters       []Interceptor
	predicates   []predicate.Nurse
	withEmployee *EmployeeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NurseQuery builder.
func (nq *NurseQuery) Where(ps ...predicate.Nurse) *NurseQuery {
	nq.predicates = append(nq.predicates, ps...)
	return nq
}

// Limit the number of records to be returned by this query.
func (nq *NurseQuery) Limit(limit int) *NurseQuery {
	nq.ctx.Limit = &limit
	return nq
}

// Offset to start from.
func (nq *NurseQuery) Offset(offset int) *NurseQuery {
	nq.ctx.Offset = &offset
	return nq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nq *NurseQuery) Unique(unique bool) *NurseQuery {
	nq.ctx.Unique = &unique
	return nq
}

// Order specifies how the records should be ordered.
func (nq *NurseQuery) Order(o ...nurse.OrderOption) *NurseQuery {
	nq.order = append(nq.order, o...)
	return nq
}

// QueryEmployee chains the current query on the "employee" edge.
func (nq *NurseQuery) QueryEmployee() *EmployeeQuery {
	query := (&EmployeeClient{config: nq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nurse.Table, nurse.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, nurse.EmployeeTable, nurse.EmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(nq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Nurse entity from the query.
// Returns a *NotFoundError when no Nurse was found.
func (nq *NurseQuery) First(ctx context.Context) (*Nurse, error) {
	nodes, err := nq.Limit(1).All(setContextOp(ctx, nq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nurse.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nq *NurseQuery) FirstX(ctx context.Context) *Nurse {
	node, err := nq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Nurse ID from the query.
// Returns a *NotFoundError when no Nurse ID was found.
func (nq *NurseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nq.Limit(1).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nurse.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nq *NurseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := nq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Nurse entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Nurse entity is found.
// Returns a *NotFoundError when no Nurse entities are found.
func (nq *NurseQuery) Only(ctx context.Context) (*Nurse, error) {
	nodes, err := nq.Limit(2).All(setContextOp(ctx, nq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nurse.Label}
	default:
		return nil, &NotSingularError{nurse.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nq *NurseQuery) OnlyX(ctx context.Context) *Nurse {
	node, err := nq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Nurse ID in the query.
// Returns a *NotSingularError when more than one Nurse ID is found.
// Returns a *NotFoundError when no entities are found.
func (nq *NurseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nq.Limit(2).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nurse.Label}
	default:
		err = &NotSingularError{nurse.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nq *NurseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := nq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Nurses.
func (nq *NurseQuery) All(ctx context.Context) ([]*Nurse, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryAll)
	if err := nq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Nurse, *NurseQuery]()
	return withInterceptors[[]*Nurse](ctx, nq, qr, nq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nq *NurseQuery) AllX(ctx context.Context) []*Nurse {
	nodes, err := nq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Nurse IDs.
func (nq *NurseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if nq.ctx.Unique == nil && nq.path != nil {
		nq.Unique(true)
	}
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryIDs)
	if err = nq.Select(nurse.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nq *NurseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := nq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nq *NurseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryCount)
	if err := nq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nq, querierCount[*NurseQuery](), nq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nq *NurseQuery) CountX(ctx context.Context) int {
	count, err := nq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nq *NurseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryExist)
	switch _, err := nq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nq *NurseQuery) ExistX(ctx context.Context) bool {
	exist, err := nq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NurseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nq *NurseQuery) Clone() *NurseQuery {
	if nq == nil {
		return nil
	}
	return &NurseQuery{
		config:       nq.config,
		ctx:          nq.ctx.Clone(),
		order:        append([]nurse.OrderOption{}, nq.order...),
		inters:       append([]Interceptor{}, nq.inters...),
		predicates:   append([]predicate.Nurse{}, nq.predicates...),
		withEmployee: nq.withEmployee.Clone(),
		// clone intermediate query.
		sql:  nq.sql.Clone(),
		path: nq.path,
	}
}

// WithEmployee tells the query-builder to eager-load the nodes that are connected to
// the "employee" edge. The optional arguments are used to configure the query builder of the edge.
func (nq *NurseQuery) WithEmployee(opts ...func(*EmployeeQuery)) *NurseQuery {
	query := (&EmployeeClient{config: nq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nq.withEmployee = query
	return nq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NurseID uuid.UUID `json:"nurse_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Nurse.Query().
//		GroupBy(nurse.FieldNurseID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nq *NurseQuery) GroupBy(field string, fields ...string) *NurseGroupBy {
	nq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NurseGroupBy{build: nq}
	grbuild.flds = &nq.ctx.Fields
	grbuild.label = nurse.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NurseID uuid.UUID `json:"nurse_id,omitempty"`
//	}
//
//	client.Nurse.Query().
//		Select(nurse.FieldNurseID).
//		Scan(ctx, &v)
func (nq *NurseQuery) Select(fields ...string) *NurseSelect {
	nq.ctx.Fields = append(nq.ctx.Fields, fields...)
	sbuild := &NurseSelect{NurseQuery: nq}
	sbuild.label = nurse.Label
	sbuild.flds, sbuild.scan = &nq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NurseSelect configured with the given aggregations.
func (nq *NurseQuery) Aggregate(fns ...AggregateFunc) *NurseSelect {
	return nq.Select().Aggregate(fns...)
}

func (nq *NurseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nq); err != nil {
				return err
			}
		}
	}
	for _, f := range nq.ctx.Fields {
		if !nurse.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nq.path != nil {
		prev, err := nq.path(ctx)
		if err != nil {
			return err
		}
		nq.sql = prev
	}
	return nil
}

func (nq *NurseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Nurse, error) {
	var (
		nodes       = []*Nurse{}
		_spec       = nq.querySpec()
		loadedTypes = [1]bool{
			nq.withEmployee != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Nurse).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Nurse{config: nq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nq.withEmployee; query != nil {
		if err := nq.loadEmployee(ctx, query, nodes, nil,
			func(n *Nurse, e *Employee) { n.Edges.Employee = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nq *NurseQuery) loadEmployee(ctx context.Context, query *EmployeeQuery, nodes []*Nurse, init func(*Nurse), assign func(*Nurse, *Employee)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Nurse)
	for i := range nodes {
		fk := nodes[i].NurseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(employee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "nurse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nq *NurseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nq.querySpec()
	_spec.Node.Columns = nq.ctx.Fields
	if len(nq.ctx.Fields) > 0 {
		_spec.Unique = nq.ctx.Unique != nil && *nq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nq.driver, _spec)
}

func (nq *NurseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nurse.Table, nurse.Columns, sqlgraph.NewFieldSpec(nurse.FieldID, field.TypeUUID))
	_spec.From = nq.sql
	if unique := nq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nq.path != nil {
		_spec.Unique = true
	}
	if fields := nq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nurse.FieldID)
		for i := range fields {
			if fields[i] != nurse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if nq.withEmployee != nil {
			_spec.Node.AddColumnOnce(nurse.FieldNurseID)
		}
	}
	if ps := nq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nq *NurseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nq.driver.Dialect())
	t1 := builder.Table(nurse.Table)
	columns := nq.ctx.Fields
	if len(columns) == 0 {
		columns = nurse.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nq.sql != nil {
		selector = nq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nq.ctx.Unique != nil && *nq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nq.predicates {
		p(selector)
	}
	for _, p := range nq.order {
		p(selector)
	}
	if offset := nq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NurseGroupBy is the group-by builder for Nurse entities.
type NurseGroupBy struct {
	selector
	build *NurseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ngb *NurseGroupBy) Aggregate(fns ...AggregateFunc) *NurseGroupBy {
	ngb.fns = append(ngb.fns, fns...)
	return ngb
}

// Scan applies the selector query and scans the result into the given value.
func (ngb *NurseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ngb.build.ctx, ent.OpQueryGroupBy)
	if err := ngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NurseQuery, *NurseGroupBy](ctx, ngb.build, ngb, ngb.build.inters, v)
}

func (ngb *NurseGroupBy) sqlScan(ctx context.Context, root *NurseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ngb.fns))
	for _, fn := range ngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ngb.flds)+len(ngb.fns))
		for _, f := range *ngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NurseSelect is the builder for selecting fields of Nurse entities.
type NurseSelect struct {
	*NurseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ns *NurseSelect) Aggregate(fns ...AggregateFunc) *NurseSelect {
	ns.fns = append(ns.fns, fns...)
	return ns
}

// Scan applies the selector query and scans the result into the given value.
func (ns *NurseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ns.ctx, ent.OpQuerySelect)
	if err := ns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NurseQuery, *NurseSelect](ctx, ns.NurseQuery, ns, ns.inters, v)
}

func (ns *NurseSelect) sqlScan(ctx context.Context, root *NurseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ns.fns))
	for _, fn := range ns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
