// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auth/ent/auth"
	"auth/ent/department"
	"auth/ent/doctor"
	"auth/ent/employee"
	"auth/ent/nurse"
	"auth/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authFields := schema.Auth{}.Fields()
	_ = authFields
	// authDescCreatedDate is the schema descriptor for created_date field.
	authDescCreatedDate := authFields[5].Descriptor()
	// auth.DefaultCreatedDate holds the default value on creation for the created_date field.
	auth.DefaultCreatedDate = authDescCreatedDate.Default.(time.Time)
	// authDescLastModifiedDate is the schema descriptor for last_modified_date field.
	authDescLastModifiedDate := authFields[6].Descriptor()
	// auth.DefaultLastModifiedDate holds the default value on creation for the last_modified_date field.
	auth.DefaultLastModifiedDate = authDescLastModifiedDate.Default.(time.Time)
	// authDescID is the schema descriptor for id field.
	authDescID := authFields[0].Descriptor()
	// auth.DefaultID holds the default value on creation for the id field.
	auth.DefaultID = authDescID.Default.(func() uuid.UUID)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentFields[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(func() uuid.UUID)
	doctorFields := schema.Doctor{}.Fields()
	_ = doctorFields
	// doctorDescID is the schema descriptor for id field.
	doctorDescID := doctorFields[0].Descriptor()
	// doctor.DefaultID holds the default value on creation for the id field.
	doctor.DefaultID = doctorDescID.Default.(func() uuid.UUID)
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCode is the schema descriptor for code field.
	employeeDescCode := employeeFields[6].Descriptor()
	// employee.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	employee.CodeValidator = employeeDescCode.Validators[0].(func(string) error)
	// employeeDescID is the schema descriptor for id field.
	employeeDescID := employeeFields[0].Descriptor()
	// employee.DefaultID holds the default value on creation for the id field.
	employee.DefaultID = employeeDescID.Default.(func() uuid.UUID)
	nurseFields := schema.Nurse{}.Fields()
	_ = nurseFields
	// nurseDescID is the schema descriptor for id field.
	nurseDescID := nurseFields[0].Descriptor()
	// nurse.DefaultID holds the default value on creation for the id field.
	nurse.DefaultID = nurseDescID.Default.(func() uuid.UUID)
}
